[platformio]
default_envs = esp-ntp-xiao
src_dir = main

[env:esp-ntp-xiao]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200

# Custom partition table
board_build.partitions = partitions.csv

# ESP-IDF specific settings
build_flags = 
    -DCORE_DEBUG_LEVEL=3

# PlatformIO IDF project settings
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio

# Serial port configuration
upload_speed = 921600
